/*
 * A simple app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/Thiryn/sample-api/internal/api"
	"log"
	"net/http"

	openapi "github.com/Thiryn/sample-api/gen/go"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := api.NewDefaultApiService()
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	router := openapi.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
