/*
 * A simple app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	openapi "github.com/Thiryn/sample-api/gen/go"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"net/http"
)

const (
	awsRegion = "eu-west-2"
	bucket    = "dorian-test"
)

// DefaultApiService is a service that implements the logic for the DefaultApiService
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	S3Client *s3.Client
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() openapi.DefaultApiService {
	return &DefaultApiService{S3Client: s3.New(s3.Options{Region: "eu-west-2"})}
}

// FilesGet -
func (s *DefaultApiService) FilesGet(ctx context.Context) (openapi.ImplResponse, error) {
	res, err := s.S3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
		Bucket: aws.String(bucket),
	})
	if err != nil {
		return openapi.Response(http.StatusInternalServerError, nil), err
	}
	files := []openapi.FilesGet200ResponseInner{}
	for _, f := range res.Contents {
		files = append(files, openapi.FilesGet200ResponseInner{
			FileName: *f.Key,
		})
	}
	return openapi.Response(http.StatusOK, files), nil
}
